// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SotfwareCine.API.Data;

#nullable disable

namespace SotfwareCine.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231112132206_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SotfwareCine.Shared.Entities.Horario", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<DateTime>("Hhorario")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTeatro")
                        .HasColumnType("int");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdTeatro");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("SotfwareCine.Shared.Entities.Teatro", b =>
                {
                    b.Property<int>("IdTeatro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTeatro"));

                    b.Property<string>("NTeatro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTeatro");

                    b.ToTable("Teatros");
                });

            modelBuilder.Entity("SotfwareCine.Shared.Entities.Horario", b =>
                {
                    b.HasOne("SotfwareCine.Shared.Entities.Teatro", "Teatro")
                        .WithMany("Horarios")
                        .HasForeignKey("IdTeatro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teatro");
                });

            modelBuilder.Entity("SotfwareCine.Shared.Entities.Teatro", b =>
                {
                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
